name: My workflow
on:
  push:
    branches:
      - main
permissions:
      contents: read
      pages: write
      id-token: write      
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: action1
        uses: actions/checkout@v4

      - name: action2
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1