name: My workflow
on:
  push:
    branches:
      - main
jobs:
  my-job:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: action1
        uses: actions/checkout@v3

      - name: action2
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # correct input name
